Create database dbElectrodomesticos;



create table CLIENTE(
CODCLI char(4) NOT NULL,
NOMCLI VArCHar(60) NOT NULL,
APECLI VARCHAR(80) NOT NULL,
EMACLI VARCHAR(80) NOT NULL,
CELCLI CHAR(9) NOT NULL,
DIRCLI VARCHAR (70) NOT NULL,
ESTCLI CHAR(1) NOT NULL
CONSTRAINT CODCLI_pk PRIMARY KEY (CODCLI));

create table VENDEDOR( 
CODVEND char(4) NOT NULL,
NOMVEND VArCHar(60) NOT NULL,
APEVEND VARCHAR(80) NOT NULL,
EMAVNED VARCHAR(80) NOT NULL,
CELVEND CHAR(9) NOT NULL,
DIRVEND VARCHAR (70) NOT NULL,
ESTVEND CHAR(1) NOT NULL
CONSTRAINT CODVEND_pk PRIMARY KEY (CODVEND));

create table PRODUCTO(
CODPRO VARCHAR (5) NOT NULL,
DESCPRO VArCHar(80) NOT NULL,
CATPRO CHAR(1) NOT NULL,
PREPRO DECIMAL(8,2) NOT NULL,
STOCKPRO INT NOT NULL,
ESTPRO CHAR(1) NOT NULL
CONSTRAINT CODPRO_pk PRIMARY KEY (CODPRO));

CREATE PROCEDURE spInserVendedor
(
  @CODVEND char(6),
  @NOMVEND nvarchar(60),
  @APEVEND nvarchar(60),
  @EMAVNED nvarchar(60),
  @CELVEND nvarchar(60),
  @DIRVEND nvarchar(60),
  @ESTVEND nvarchar(60)
  )
 AS 
 BEGIN 
SET NOCOUNT ON 
INSERT INTO  CLIENTE 
(CODCLI,NOMCLI,APECLI,EMACLI,CELCLI,DIRCLI,ESTCLI)
VALUES 
(@CODVEND, @NOMVEND, @APEVEND, @EMAVNED, @CELVEND, @DIRVEND, @ESTVEND)

SELECT * FROM VENDEDOR
WHERE @CODVEND = @CODVEND
END 
GO

create table VENTA (
CODVEN char(5) NOT NULL,
FECVEN DATETIME NOT NULL,
CODCLI CHAR(4) NOT NULL,
CODVEND CHAR(4) NOT NULL,
ESTVEN CHAR(1) NOT NULL
CONSTRAINT CODVEN_pk PRIMARY KEY (CODVEN));



create table VENTADETALLE (
IDVENDET int identity (1,1) NOT NULL,
CODVEN CHar(5) NOT NULL,
CODPRO varCHAR(5) NOT NULL,
CANTPRO int NOT NULL
CONSTRAINT IDVENDET_pk PRIMARY KEY (IDVENDET));

create table PROVEEDOR(
CODPROV char(5) NOT NULL,
RAZSOCPROV VArCHar(90) NOT NULL,
RUCPROV VARCHAR(11) NOT NULL,
EMAPROV VARCHAR(70) NOT NULL,
ESTPROV CHAR(1) NOT NULL
CONSTRAINT CODPROV_pk PRIMARY KEY (CODPROV));

create table COMPRA (
CODCOM char(5) NOT NULL,
FECCOM DATETIME NOT NULL,
CODVEND CHAR(4) NOT NULL,
CODPROV CHAR(5) NOT NULL,
ESTCOM CHAR(1) NOT NULL
CONSTRAINT CODCOM_pk PRIMARY KEY (CODCOM));

create table COMPRADETALLE(
IDCOMDET INT IDENTITY(1,1) NOT NULL,
CODCOM CHar(5) NOT NULL,
CODPRO varCHAR(5) NOT NULL,
CANTPRO  int NOT NULL
CONSTRAINT IDCENDET_pk PRIMARY KEY (IDCOMDET));

ALTER TABLE VENTA ADD CONSTRAINT VENTA_VENDEDOR
    FOREIGN KEY (CODVEND)
    REFERENCES VENDEDOR (CODVEND) 
GO
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_VENDEDOR
    FOREIGN KEY (CODVEND)
    REFERENCES VENDEDOR (CODVEND) 
GO

ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (CODCLI)
    REFERENCES CLIENTE (CODCLI) 
GO
ALTER TABLE VENTADETALLE ADD CONSTRAINT VENTADETALLE_VENTA
    FOREIGN KEY (CODVEN)
    REFERENCES VENTA (CODVEN) 
GO
ALTER TABLE COMPRADETALLE ADD CONSTRAINT COMPRADETALLE_COMPRA
    FOREIGN KEY (CODCOM)
    REFERENCES COMPRA (CODCOM) 
GO

ALTER TABLE VENTADETALLE ADD CONSTRAINT VENTADETALLE_PRODUCTO
    FOREIGN KEY (CODPRO)
    REFERENCES PRODUCTO (CODPRO) 
GO

ALTER TABLE COMPRADETALLE ADD CONSTRAINT COMPRADETALLE_PRODUCTO
    FOREIGN KEY (CODPRO)
    REFERENCES PRODUCTO (CODPRO) 
GO
ALTER TABLE COMPRADETALLE ADD CONSTRAINT COMPRADETALLE_COMPRA
    FOREIGN KEY (CODCOM)
    REFERENCES COMPRA (CODCOM) 
GO

ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_PROVEEDOR
    FOREIGN KEY (CODPROV)
    REFERENCES PROVEEDOR (CODPROV) 
GO



INSERT INTO CLIENTE
(CODCLI,NOMCLI,APECLI,EMACLI,CELCLI,DIRCLI,ESTCLI)
VALUES
('CL01','JUANA','CAMPOS ORTIZ','juana.campos@gmail.com','98748552','Av.Miraflores','A'),
('CL02','Sofia','Barrios Salcedo','sofia.barrios@outlook.com','','Jr.Huallaga','A'),
('CL03','Claudio','Perez Luna','claudio.perez@outlook.com','984512447','Av.Libertadores','A'),
('CL04','Marcos','Avila Manco','marcos.avila@yahoo.com','','Calle Huallaga','A'),
('CL05','Anastasio','Salomon Inti','anastasio.salomon@gmail.com','','Jr.San Martin','A');


INSERT INTO VENDEDOR
(CODVEND,NOMVEND,APEVEND,EMAVNED,CELVEND,DIRVEND,ESTVEND)
VALUES
('VEN1','GLoria','Carrizales Paredes','gloria.carrizales@gmail.com','984574123','Calle Las Begonias','A'),
('VEN2','Gabriel','Lozada Lombardi','gabriel.lozada@gmail.com','974512368','Av. Los Girasoles','A'),
('VEN3','Gilberto','Martinez Guerra','gilberto.martinez@gmail.com','','jr Palomares','A');

INSERT INTO PROVEEDOR
(CODPROV,RAZSOCPROV,RUCPROV,EMAPROV,ESTPROV)
VALUES
('PRV01','LG Corportation','87542136951','imformes@lg.com.pe','A'),
('PRV02','SONY','45213698741','imformes@sony.com.pe','A'),
('PRV03','SAMSUNG','85321697661','imformes@samsung.com.pe','A'),
('PRV04','OSTER SRL','55663214478','imformes@oster.com.pe','A'),
('PRV05','ASUS','99663325478','imformes@asus.com.pe','A');

insert into PRODUCTO
(CODPRO,DESCPRO,CATPRO,PREPRO,STOCKPRO,ESTPRO)
values
('PRO02','Refrigeradora SBS 602L','1','3599','10','A'),
('PRO03','Refrigeradora Top Mount 500 L','2','2799','8','A'),
('PRO04','TV SAMSUNG UHD 55','2','1799','25','A'),
('PRO05','Televisor 65" LG UHD 4k','3','2999','20','A'),
('PRO06','TV CRYSTAL UHD 55','3','2299','7','A'),
('PRO07','ASUS X415JA Core i3 10a Gen 14" ','3','1099','17','A'),
('PRO08','Lenovo IdeaPad 5i Intel Core i7 14"','3','3099','10','A'),
('PRO09','Laptop HP 15-dw1085la Intel Core i3','3','1600','15','A'),
('PRO10','Galaxy A52 128GB','4','1200','25','A'),
('PRO11','Iphone 11 64GB Morado','4','2600','30','A'),
('PRO12','Poco X3 GT 5G 256GB 8GB','4','1450','20','A');

select * from producto;
drop table PRODUCTO;

-- Creamos el PROCEDURE para registrar Datos
SELECT * FROM CLIENTE
GO
CREATE PROCEDURE spInserCliente
(
  @CODCLI char(6),
  @NOMCLI nvarchar(60),
  @APECLI nvarchar(60),
  @EMACLI nvarchar(60),
  @CELCLI nvarchar(60),
  @DIRCLI nvarchar(60),
  @ESTCLI nvarchar(60)
  )
 AS 
 BEGIN 
SET NOCOUNT ON 
INSERT INTO  CLIENTE 
(CODCLI,NOMCLI,APECLI,EMACLI,CELCLI,DIRCLI,ESTCLI)
VALUES 
(@CODCLI, @NOMCLI, @APECLI, @EMACLI, @CELCLI, @DIRCLI, @ESTCLI)

SELECT * FROM CLIENTE
WHERE CODCLI = @CODCLI
END 
GO
